/**
 * Incident Intelligence Detail Screen
 *
 * A dedicated screen for viewing detailed incident intelligence,
 * accessible from the Civic Map or Activity screen.
 *
 * Data loading order:
 * 1. Try Supabase (real incident owned by the user)
 * 2. Fall back to mock data (demo incidents from the map)
 *
 * Mock "AI intelligence" sections are only shown for mock incidents.
 * Real incidents display only verified database data.
 */

import { useEffect, useState } from 'react';
import {
  ActivityIndicator,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import {
  Button,
  Card,
  Icon,
  StatusBadge,
  colors,
  radius,
  spacing,
  touchTarget,
  typography,
  type IncidentStatus,
  type IconName,
} from '../../src/design';
import {
  findMockIncident,
  SEVERITY_CONFIG,
  type MockIncident,
  type Severity,
} from '../../src/data/mock-incidents';
import {
  fetchIncidentById,
  type IncidentRow,
} from '../../src/services/incident';
import {
  analyzeIncident,
  type IntelligenceResponse,
} from '../../src/services/intelligence';
import {
  CATEGORIES,
  toUiStatus,
  formatReportedAgo,
} from '../../src/constants/civic';

// ── AI Severity → UI Severity Mapping ────────────────────────────

const AI_SEVERITY_TO_UI: Record<string, Severity> = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  critical: 'critical',
};

function aiSeverityToUi(severity: string | null): Severity {
  if (!severity) return 'medium';
  return AI_SEVERITY_TO_UI[severity] ?? 'medium';
}

// ── Intelligence State ───────────────────────────────────────────

type IntelligenceState = 'idle' | 'loading' | 'ready' | 'unavailable' | 'error';

// ── Source-Aware Labels ──────────────────────────────────────────

const SOURCE_LABELS: Record<
  string,
  { header: string; badge: string; disclaimer: string }
> = {
  ai_model: {
    header: 'AI Assessment',
    badge: 'BASED ON SUBMITTED DATA',
    disclaimer:
      'This analysis is generated by AI and requires verification by authorities.',
  },
  rules_engine: {
    header: 'Civic Assessment',
    badge: 'AUTOMATED ASSESSMENT',
    disclaimer:
      'Based on the information submitted by the reporter. Verification is required before taking official action.',
  },
};

function getSourceLabels(source: string | null) {
  if (source && SOURCE_LABELS[source]) return SOURCE_LABELS[source];
  // Default to civic assessment labels for unknown sources
  return SOURCE_LABELS.rules_engine;
}

// ── Unified Incident View ────────────────────────────────────────

interface IncidentViewData {
  id: string;
  category: string;
  title: string;
  description: string;
  severity: Severity;
  status: IncidentStatus;
  area: string;
  reportedAgo: string;
  /** Whether this is from mock data (enables AI sections) */
  isMock: boolean;
  // Mock-only intelligence fields
  whatHappened?: string;
  likelyImpact?: string;
  confidence?: 'low' | 'medium' | 'high';
  impactChain?: string[];
  recommendedAction?: string;
}

// ── Unified Incident View ─────────────────────────────────────────

function fromSupabase(incident: IncidentRow): IncidentViewData {
  return {
    id: incident.id,
    category: incident.category,
    title: incident.title,
    description: incident.description,
    severity: 'medium',
    status: toUiStatus(incident.status),
    area:
      incident.latitude !== 0
        ? `${incident.latitude.toFixed(4)}, ${incident.longitude.toFixed(4)}`
        : 'Location not recorded',
    reportedAgo: formatReportedAgo(incident.reported_at),
    isMock: false,
  };
}

function fromMock(incident: MockIncident): IncidentViewData {
  return {
    id: incident.id,
    category: incident.category,
    title: incident.title,
    description: incident.description,
    severity: incident.severity,
    status: incident.status,
    area: incident.area,
    reportedAgo: incident.reportedAgo,
    isMock: true,
    whatHappened: incident.whatHappened,
    likelyImpact: incident.likelyImpact,
    confidence: incident.confidence,
    impactChain: incident.impactChain,
    recommendedAction: incident.recommendedAction,
  };
}

// ── Lifecycle Statuses ───────────────────────────────────────────

const LIFECYCLE_STATUSES: IncidentStatus[] = [
  'REPORTED',
  'AI_ANALYZED',
  'CORROBORATED',
  'VERIFIED',
  'IN_PROGRESS',
  'RESOLVED',
];

const STATUS_PROGRESS_INDEX: Record<IncidentStatus, number> = {
  REPORTED: 0,
  AI_ANALYZED: 1,
  CORROBORATED: 2,
  VERIFIED: 3,
  IN_PROGRESS: 4,
  RESOLVED: 5,
  REJECTED: -1,
};

// ── Main Screen ──────────────────────────────────────────────────

export default function IncidentDetailScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();

  const [incident, setIncident] = useState<IncidentViewData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [intelligence, setIntelligence] = useState<IntelligenceResponse | null>(null);
  const [intelligenceState, setIntelligenceState] = useState<IntelligenceState>('idle');

  useEffect(() => {
    let cancelled = false;

    async function load() {
      if (!id) {
        if (!cancelled) setIsLoading(false);
        return;
      }

      // 1. Try Supabase (real incident)
      let realIncident: IncidentRow | null = null;
      try {
        const result = await fetchIncidentById(id);
        if (result.incident) {
          realIncident = result.incident;
        }
      } catch {
        // Supabase not available — continue to mock fallback
      }

      if (realIncident && !cancelled) {
        setIncident(fromSupabase(realIncident));
        setIsLoading(false);

        // 2. Request intelligence for real incidents
        setIntelligenceState('loading');
        try {
          const intel = await analyzeIncident({
            title: realIncident.title,
            description: realIncident.description,
            category: realIncident.category,
            latitude: realIncident.latitude,
            longitude: realIncident.longitude,
          });

          if (!cancelled) {
            setIntelligence(intel);
            if (intel.status === 'success' && intel.available) {
              setIntelligenceState('ready');
            } else if (intel.status === 'unavailable') {
              setIntelligenceState('unavailable');
            } else {
              setIntelligenceState('error');
            }
          }
        } catch {
          // Safety net — should never reach here because analyzeIncident()
          // has its own fallback, but guard against unexpected failures.
          if (!cancelled) {
            setIntelligenceState('error');
          }
        }
        return;
      }

      // 3. Fall back to mock data (map demo incidents)
      const mockIncident = findMockIncident(id);
      if (mockIncident && !cancelled) {
        setIncident(fromMock(mockIncident));
      }

      if (!cancelled) setIsLoading(false);
    }

    load();
    return () => {
      cancelled = true;
    };
  }, [id]);

  // ── Loading State ──────────────────────────────────────────────

  if (isLoading) {
    return (
      <SafeAreaView style={styles.screen}>
        <View style={styles.header}>
          <Pressable
            onPress={() => router.back()}
            style={styles.backBtn}
            accessibilityRole="button"
            accessibilityLabel="Go back"
          >
            <Icon name="back" size={20} color={colors.primary} />
          </Pressable>
          <Text style={styles.headerTitle}>Incident Intelligence</Text>
          <View style={styles.headerSpacer} />
        </View>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.loadingText}>Loading incident…</Text>
        </View>
      </SafeAreaView>
    );
  }

  // ── Not Found ──────────────────────────────────────────────────

  if (!incident) {
    return (
      <SafeAreaView style={styles.screen}>
        <View style={styles.notFound}>
          <Icon name="info" size={32} color={colors.textTertiary} />
          <Text style={styles.notFoundText}>Incident not found</Text>
          <Button variant="secondary" size="md" label="Go back" onPress={() => router.back()} />
        </View>
      </SafeAreaView>
    );
  }

  // ── Incident Detail ────────────────────────────────────────────

  return (
    <SafeAreaView style={styles.screen} edges={['top']}>
      {/* ── Header ──────────────────────────────────────────── */}
      <View style={styles.header}>
        <Pressable
          onPress={() => router.back()}
          style={styles.backBtn}
          accessibilityRole="button"
          accessibilityLabel="Go back"
        >
          <Icon name="back" size={20} color={colors.primary} />
        </Pressable>
        <Text style={styles.headerTitle}>Incident Intelligence</Text>
        <View style={styles.headerSpacer} />
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* ── Incident Overview ─────────────────────────────── */}
        <IncidentOverview
          incident={incident}
          intelligence={incident.isMock ? null : intelligence}
        />

        {/* ── Lifecycle Section ─────────────────────────────── */}
        <LifecycleSection status={incident.status} />

        {/* ── Real Intelligence (for Supabase incidents) ────── */}
        {!incident.isMock && (
          <RealIntelligenceSection
            state={intelligenceState}
            intelligence={intelligence}
          />
        )}

        {/* ── Mock AI sections (only for demo incidents) ────── */}
        {incident.isMock && incident.whatHappened && (
          <AIUnderstandingSection incident={incident} />
        )}
        {incident.isMock && incident.impactChain && (
          <CivicImpactSection impactChain={incident.impactChain} />
        )}
        {incident.isMock && incident.recommendedAction && (
          <WhatHappensNextSection action={incident.recommendedAction} />
        )}

        {/* ── Verification Explanation ──────────────────────── */}
        <VerificationSection />

        {/* ── Back ──────────────────────────────────────────── */}
        <View style={styles.footer}>
          <Button variant="secondary" size="lg" label="Go back" onPress={() => router.back()} />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

// ── Incident Overview Component ──────────────────────────────────

function IncidentOverview({
  incident,
  intelligence,
}: {
  incident: IncidentViewData;
  intelligence: IntelligenceResponse | null;
}) {
  const catConfig =
    CATEGORIES[incident.category] ?? CATEGORIES.other;

  // Use AI-derived severity for real incidents, mock severity for mock
  const effectiveSeverity = intelligence?.severity
    ? aiSeverityToUi(intelligence.severity)
    : incident.severity;
  const severityConfig = SEVERITY_CONFIG[effectiveSeverity];
  const incidentType = intelligence?.incident_type ?? null;

  return (
    <Card padding="lg" elevation="sm" style={styles.overviewCard}>
      {/* Category + Severity Row */}
      <View style={styles.overviewMeta}>
        <View style={[styles.categoryChip, { backgroundColor: catConfig.color + '15' }]}>
          <Icon name={catConfig.icon} size={14} color={catConfig.color} />
          <Text style={[styles.categoryChipText, { color: catConfig.color }]}>
            {catConfig.label}
          </Text>
        </View>
        <View style={styles.severityBadge}>
          <View style={[styles.severityDot, { backgroundColor: severityConfig.color }]} />
          <Text style={[styles.severityText, { color: severityConfig.color }]}>
            {severityConfig.label} severity
          </Text>
        </View>
      </View>

      {/* Title */}
      <Text style={styles.incidentTitle}>{incident.title}</Text>

      {/* AI-derived incident type (real incidents only) */}
      {incidentType && (
        <Text style={styles.incidentType}>{incidentType}</Text>
      )}

      {/* Location + Time */}
      <View style={styles.locationRow}>
        <Icon name="location" size={14} color={colors.textSecondary} />
        <Text style={styles.locationText}>{incident.area}</Text>
      </View>
      <View style={styles.timeRow}>
        <Icon name="clock" size={14} color={colors.textTertiary} />
        <Text style={styles.timeText}>Reported {incident.reportedAgo}</Text>
      </View>

      {/* Current Status */}
      <View style={styles.statusRow}>
        <Text style={styles.statusLabel}>Current status</Text>
        <StatusBadge status={incident.status} size="md" />
      </View>

      {/* Description */}
      <View style={styles.descriptionBox}>
        <Text style={styles.descriptionLabel}>Description</Text>
        <Text style={styles.descriptionText}>{incident.description}</Text>
      </View>

      {/* Evidence Placeholder */}
      <View style={styles.evidencePlaceholder}>
        <Icon name="attachment" size={18} color={colors.textTertiary} />
        <Text style={styles.evidenceText}>Evidence / media attachments</Text>
        <Text style={styles.evidenceSubtext}>
          Photo and document support will be available in a future update
        </Text>
      </View>
    </Card>
  );
}

// ── Lifecycle Section ────────────────────────────────────────────

function LifecycleSection({ status }: { status: IncidentStatus }) {
  const currentIndex = STATUS_PROGRESS_INDEX[status];
  const isRejected = status === 'REJECTED';

  return (
    <Card padding="lg" elevation="sm" style={styles.sectionCard}>
      <Text style={styles.sectionTitle}>Incident Lifecycle</Text>
      <Text style={styles.sectionSubtitle}>
        How NigraanOS tracks this issue from report to resolution
      </Text>

      <View style={styles.lifecycleList}>
        {LIFECYCLE_STATUSES.map((lifecycleStatus, index) => {
          const isCompleted = !isRejected && index < currentIndex;
          const isCurrent = !isRejected && index === currentIndex;
          const isUpcoming = !isRejected && index > currentIndex;

          return (
            <View key={lifecycleStatus} style={styles.lifecycleItem}>
              {index > 0 && (
                <View
                  style={[
                    styles.lifecycleConnector,
                    isCompleted && styles.lifecycleConnectorCompleted,
                  ]}
                />
              )}
              <View
                style={[
                  styles.lifecycleDot,
                  isCompleted && styles.lifecycleDotCompleted,
                  isCurrent && styles.lifecycleDotCurrent,
                  isUpcoming && styles.lifecycleDotUpcoming,
                ]}
              >
                {isCompleted && <Icon name="check" size={10} color={colors.success} />}
                {isCurrent && <View style={styles.lifecycleDotInner} />}
              </View>
              <Text
                style={[
                  styles.lifecycleLabel,
                  isCompleted && styles.lifecycleLabelCompleted,
                  isCurrent && styles.lifecycleLabelCurrent,
                  isUpcoming && styles.lifecycleLabelUpcoming,
                ]}
              >
                {lifecycleStatus.replace(/_/g, ' ')}
              </Text>
            </View>
          );
        })}
      </View>

      {isRejected && (
        <View style={styles.rejectedBanner}>
          <Icon name="close" size={14} color={colors.statusRejected} />
          <Text style={styles.rejectedText}>This incident was rejected</Text>
        </View>
      )}
    </Card>
  );
}

// ── Real Intelligence Section ────────────────────────────────────

function RealIntelligenceSection({
  state,
  intelligence,
}: {
  state: IntelligenceState;
  intelligence: IntelligenceResponse | null;
}) {
  // ── Loading State ──────────────────────────────────────────
  if (state === 'loading' || state === 'idle') {
    return (
      <Card padding="lg" elevation="sm" style={styles.sectionCard}>
        <View style={styles.intelHeader}>
          <Text style={styles.sectionTitle}>Assessment</Text>
        </View>
        <View style={styles.intelLoading}>
          <ActivityIndicator size="small" color={colors.primary} />
          <Text style={styles.intelLoadingText}>
            Analyzing incident data…
          </Text>
        </View>
      </Card>
    );
  }

  // ── Unavailable State ──────────────────────────────────────
  if (state === 'unavailable') {
    return (
      <Card padding="lg" elevation="sm" style={styles.sectionCard}>
        <View style={styles.intelHeader}>
          <Text style={styles.sectionTitle}>Assessment</Text>
        </View>
        <View style={styles.intelUnavailable}>
          <Icon name="info" size={18} color={colors.textTertiary} />
          <Text style={styles.intelUnavailableText}>
            Assessment is not currently available. This incident has been
            recorded and will be reviewed.
          </Text>
        </View>
      </Card>
    );
  }

  // ── Error State ────────────────────────────────────────────
  if (state === 'error' || !intelligence) {
    return (
      <Card padding="lg" elevation="sm" style={styles.sectionCard}>
        <View style={styles.intelHeader}>
          <Text style={styles.sectionTitle}>Assessment</Text>
        </View>
        <View style={styles.intelUnavailable}>
          <Icon name="info" size={18} color={colors.warning} />
          <Text style={styles.intelUnavailableText}>
            Assessment could not be completed. The incident
            data has been saved and will be reviewed.
          </Text>
        </View>
      </Card>
    );
  }

  // ── Ready State ────────────────────────────────────────────
  const sourceLabels = getSourceLabels(intelligence.source);
  const confidence = intelligence.confidence ?? 50;
  const confidenceLevel =
    confidence >= 75 ? 'high' : confidence >= 45 ? 'medium' : 'low';
  const confidenceColor =
    confidenceLevel === 'high'
      ? colors.success
      : confidenceLevel === 'medium'
        ? colors.warning
        : colors.textSecondary;

  const severityUi = intelligence.severity
    ? {
        low: { label: 'Low', color: colors.success },
        medium: { label: 'Medium', color: colors.warning },
        high: { label: 'High', color: '#E65100' },
        critical: { label: 'Critical', color: colors.statusRejected },
      }[intelligence.severity] ?? { label: 'Unknown', color: colors.textTertiary }
    : { label: 'Unknown', color: colors.textTertiary };

  return (
    <Card padding="lg" elevation="sm" style={styles.sectionCard}>
      {/* Header with source-aware trust label */}
      <View style={styles.intelHeader}>
        <Text style={styles.sectionTitle}>{sourceLabels.header}</Text>
        <View style={styles.intelBadge}>
          <Text style={styles.intelBadgeText}>{sourceLabels.badge}</Text>
        </View>
      </View>
      <Text style={styles.intelDisclaimer}>
        {sourceLabels.disclaimer}
      </Text>

      {/* Summary */}
      {intelligence.summary && (
        <View style={styles.intelBlock}>
          <Text style={styles.intelLabel}>What NigraanOS found</Text>
          <Text style={styles.intelText}>{intelligence.summary}</Text>
        </View>
      )}

      {/* Severity + Confidence row */}
      <View style={styles.intelMetrics}>
        <View style={styles.intelMetric}>
          <Text style={styles.intelMetricLabel}>Severity</Text>
          <View
            style={[
              styles.intelMetricBadge,
              { backgroundColor: severityUi.color + '15' },
            ]}
          >
            <View
              style={[styles.intelMetricDot, { backgroundColor: severityUi.color }]}
            />
            <Text style={[styles.intelMetricValue, { color: severityUi.color }]}>
              {severityUi.label}
            </Text>
          </View>
        </View>
        <View style={styles.intelMetric}>
          <Text style={styles.intelMetricLabel}>Confidence</Text>
          <View
            style={[
              styles.intelMetricBadge,
              { backgroundColor: confidenceColor + '15' },
            ]}
          >
            <View
              style={[styles.intelMetricDot, { backgroundColor: confidenceColor }]}
            />
            <Text style={[styles.intelMetricValue, { color: confidenceColor }]}>
              {confidence}%
            </Text>
          </View>
        </View>
      </View>

      {/* Urgency reason */}
      {intelligence.urgency_reason && (
        <View style={styles.intelBlock}>
          <Text style={styles.intelLabel}>Why this severity</Text>
          <Text style={styles.intelText}>{intelligence.urgency_reason}</Text>
        </View>
      )}

      {/* Potential impacts */}
      {intelligence.potential_impacts.length > 0 && (
        <View style={styles.intelBlock}>
          <Text style={styles.intelLabel}>Potential impacts</Text>
          <View style={styles.intelList}>
            {intelligence.potential_impacts.map((impact, i) => (
              <View key={i} style={styles.intelListItem}>
                <View style={styles.intelListDot} />
                <Text style={styles.intelListText}>{impact}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Recommended actions */}
      {intelligence.recommended_actions.length > 0 && (
        <View style={styles.intelBlock}>
          <Text style={styles.intelLabel}>Recommended actions</Text>
          <View style={styles.intelList}>
            {intelligence.recommended_actions.map((action, i) => (
              <View key={i} style={styles.intelNumberedItem}>
                <View style={styles.intelNumberBadge}>
                  <Text style={styles.intelNumberText}>{i + 1}</Text>
                </View>
                <Text style={styles.intelNumberedText}>{action}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Civic Ripple */}
      {intelligence.ripple_trigger && intelligence.ripple_effects.length > 0 && (
        <View style={styles.rippleSection}>
          <Text style={styles.rippleTitle}>Civic Ripple</Text>
          <Text style={styles.rippleSubtitle}>
            How this issue could affect other services
          </Text>

          <View style={styles.rippleChain}>
            {/* Trigger — reported fact */}
            <View style={styles.rippleItem}>
              <View style={styles.rippleTriggerDot} />
              <Text style={styles.rippleTriggerText}>
                {intelligence.ripple_trigger}
              </Text>
            </View>

            {/* Effects — potential consequences */}
            {intelligence.ripple_effects.map((effect, i) => (
              <View key={i}>
                <View style={styles.rippleConnector} />
                <View style={styles.rippleItem}>
                  <View style={styles.rippleEffectDot} />
                  <Text style={styles.rippleEffectText}>{effect}</Text>
                </View>
              </View>
            ))}

            {/* Overall impact — wider civic impact */}
            {intelligence.ripple_overall_impact && (
              <View>
                <View style={styles.rippleConnector} />
                <View style={styles.rippleItem}>
                  <View style={styles.rippleImpactDot} />
                  <Text style={styles.rippleImpactText}>
                    {intelligence.ripple_overall_impact}
                  </Text>
                </View>
              </View>
            )}
          </View>

          {/* Impact level indicator */}
          {intelligence.ripple_impact_level && (
            <View style={styles.rippleLevelRow}>
              <Text style={styles.rippleLevelLabel}>Potential impact level</Text>
              <View
                style={[
                  styles.rippleLevelBadge,
                  {
                    backgroundColor:
                      (intelligence.ripple_impact_level === 'high'
                        ? '#E65100'
                        : intelligence.ripple_impact_level === 'medium'
                          ? colors.warning
                          : colors.success) + '15',
                  },
                ]}
              >
                <View
                  style={[
                    styles.rippleLevelDot,
                    {
                      backgroundColor:
                        intelligence.ripple_impact_level === 'high'
                          ? '#E65100'
                          : intelligence.ripple_impact_level === 'medium'
                            ? colors.warning
                            : colors.success,
                    },
                  ]}
                />
                <Text
                  style={[
                    styles.rippleLevelText,
                    {
                      color:
                        intelligence.ripple_impact_level === 'high'
                          ? '#E65100'
                          : intelligence.ripple_impact_level === 'medium'
                            ? colors.warning
                            : colors.success,
                    },
                  ]}
                >
                  {intelligence.ripple_impact_level.charAt(0).toUpperCase() +
                    intelligence.ripple_impact_level.slice(1)}
                </Text>
              </View>
            </View>
          )}

          {/* Trust disclaimer */}
          <Text style={styles.rippleDisclaimer}>
            Potential impacts are inferred from the reported information and are
            not confirmed outcomes.
          </Text>
        </View>
      )}

      {/* Verification notice */}
      {intelligence.needs_verification && (
        <View style={styles.intelVerification}>
          <Text style={styles.intelVerificationText}>
            Requires physical or authority verification before action.
          </Text>
        </View>
      )}

      {/* Low confidence warning */}
      {confidenceLevel === 'low' && (
        <View style={styles.intelLowConfidence}>
          <Icon name="info" size={14} color={colors.warning} />
          <Text style={styles.intelLowConfidenceText}>
            Low confidence — limited data available for analysis.
          </Text>
        </View>
      )}
    </Card>
  );
}

// ── AI Understanding Section (MOCK only) ─────────────────────────

function AIUnderstandingSection({ incident }: { incident: IncidentViewData }) {
  const confidence = incident.confidence ?? 'medium';
  const confidenceColor =
    confidence === 'high'
      ? colors.success
      : confidence === 'medium'
        ? colors.warning
        : colors.textSecondary;

  return (
    <Card padding="lg" elevation="sm" style={styles.sectionCard}>
      <View style={styles.sectionHeaderRow}>
        <Text style={styles.sectionTitle}>AI Understanding</Text>
      </View>
      <Text style={styles.sectionSubtitle}>
        Preliminary analysis based on available information
      </Text>

      <View style={styles.intelligenceItem}>
        <Text style={styles.intelligenceLabel}>What happened</Text>
        <Text style={styles.intelligenceText}>{incident.whatHappened}</Text>
      </View>

      <View style={styles.intelligenceItem}>
        <Text style={styles.intelligenceLabel}>Likely impact</Text>
        <Text style={styles.intelligenceText}>{incident.likelyImpact}</Text>
      </View>

      <View style={styles.confidenceRow}>
        <Text style={styles.intelligenceLabel}>Confidence</Text>
        <View style={[styles.confidenceBadge, { backgroundColor: confidenceColor + '15' }]}>
          <View style={[styles.confidenceDot, { backgroundColor: confidenceColor }]} />
          <Text style={[styles.confidenceText, { color: confidenceColor }]}>
            {confidence.charAt(0).toUpperCase() + confidence.slice(1)}
          </Text>
        </View>
      </View>
    </Card>
  );
}

// ── Civic Impact Section (MOCK only) ─────────────────────────────

function CivicImpactSection({ impactChain }: { impactChain: string[] }) {
  return (
    <Card padding="lg" elevation="sm" style={styles.sectionCard}>
      <View style={styles.sectionHeaderRow}>
        <Text style={styles.sectionTitle}>Civic Impact</Text>
      </View>
      <Text style={styles.sectionSubtitle}>
        How this issue may affect the surrounding community
      </Text>

      <View style={styles.impactChain}>
        {impactChain.map((item, index) => (
          <View key={index} style={styles.impactChainItem}>
            <View style={styles.impactChainNumber}>
              <Text style={styles.impactChainNumberText}>{index + 1}</Text>
            </View>
            <Text style={styles.impactChainText}>{item}</Text>
            {index < impactChain.length - 1 && (
              <Icon name="forward" size={14} color={colors.textTertiary} />
            )}
          </View>
        ))}
      </View>
    </Card>
  );
}

// ── What Happens Next Section (MOCK only) ────────────────────────

function WhatHappensNextSection({ action }: { action: string }) {
  return (
    <Card padding="lg" elevation="sm" style={styles.sectionCard}>
      <View style={styles.sectionHeaderRow}>
        <Text style={styles.sectionTitle}>What happens next?</Text>
      </View>
      <Text style={styles.sectionSubtitle}>
        Recommended action based on similar incidents
      </Text>

      <View style={styles.recommendedAction}>
        <Icon name="info" size={18} color={colors.primary} />
        <Text style={styles.recommendedActionText}>{action}</Text>
      </View>

      <Text style={styles.recommendationDisclaimer}>
        This is a preliminary recommendation. Actual response will be coordinated
        by relevant authorities after verification.
      </Text>
    </Card>
  );
}

// ── Verification Section ─────────────────────────────────────────

function VerificationSection() {
  return (
    <Card padding="lg" elevation="sm" style={styles.verificationCard}>
      <Icon name="info" size={20} color={colors.info} />
      <Text style={styles.verificationTitle}>About verification</Text>
      <Text style={styles.verificationText}>
        Reported does not mean verified. NigraanOS uses a multi-step verification
        process that includes AI analysis, citizen corroboration, and authority
        confirmation before an issue is marked as verified.
      </Text>
      <Text style={styles.verificationText}>
        This helps ensure accuracy and prevents false reports from affecting
        civic response priorities.
      </Text>
    </Card>
  );
}

// ── Styles ───────────────────────────────────────────────────────

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },

  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  backBtn: {
    width: touchTarget.min,
    height: touchTarget.min,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.full,
    backgroundColor: colors.primaryLight,
    marginRight: spacing.md,
  },
  headerTitle: {
    ...typography.styles.heading,
    color: colors.text,
    flex: 1,
  },
  headerSpacer: {
    width: touchTarget.min,
  },

  // Loading
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
  },
  loadingText: {
    ...typography.styles.bodyMedium,
    color: colors.textSecondary,
  },

  // Scroll
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.lg,
    gap: spacing.lg,
  },

  // Not Found
  notFound: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.md,
  },
  notFoundText: {
    ...typography.styles.bodyMedium,
    color: colors.textSecondary,
  },

  // Overview Card
  overviewCard: {
    borderRadius: radius.xl,
  },
  overviewMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
  },
  categoryChipText: {
    ...typography.styles.caption,
    fontWeight: '600',
  },
  severityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  severityDot: {
    width: 8,
    height: 8,
    borderRadius: radius.full,
  },
  severityText: {
    ...typography.styles.caption,
    fontWeight: '600',
  },
  incidentTitle: {
    ...typography.styles.title,
    color: colors.text,
    marginBottom: spacing.md,
    lineHeight: 28,
  },
  incidentType: {
    ...typography.styles.bodySmall,
    color: colors.primary,
    fontWeight: '500',
    marginBottom: spacing.md,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  locationText: {
    ...typography.styles.bodySmall,
    color: colors.textSecondary,
    flex: 1,
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.lg,
  },
  timeText: {
    ...typography.styles.caption,
    color: colors.textTertiary,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  statusLabel: {
    ...typography.styles.label,
    color: colors.textSecondary,
  },
  descriptionBox: {
    marginTop: spacing.md,
  },
  descriptionLabel: {
    ...typography.styles.label,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
  },
  descriptionText: {
    ...typography.styles.bodySmall,
    color: colors.text,
    lineHeight: typography.lineHeight.relaxed,
  },
  evidencePlaceholder: {
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    alignItems: 'center',
    gap: spacing.xs,
  },
  evidenceText: {
    ...typography.styles.label,
    color: colors.textSecondary,
  },
  evidenceSubtext: {
    ...typography.styles.caption,
    color: colors.textTertiary,
    textAlign: 'center',
  },

  // Section Cards
  sectionCard: {
    borderRadius: radius.xl,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  sectionTitle: {
    ...typography.styles.heading,
    color: colors.text,
    fontSize: typography.fontSize.md,
  },
  sectionSubtitle: {
    ...typography.styles.caption,
    color: colors.textSecondary,
    marginBottom: spacing.md,
  },

  // Real Data Notice
  realDataNotice: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  realDataNoticeContent: {
    flex: 1,
    gap: spacing.xs,
  },
  realDataNoticeTitle: {
    ...typography.styles.label,
    color: colors.text,
    fontWeight: '600',
  },
  realDataNoticeText: {
    ...typography.styles.bodySmall,
    color: colors.textSecondary,
    lineHeight: typography.lineHeight.relaxed,
  },

  // Lifecycle
  lifecycleList: {
    paddingLeft: spacing.md,
  },
  lifecycleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    gap: spacing.md,
  },
  lifecycleConnector: {
    position: 'absolute',
    left: 11,
    top: -spacing.sm,
    width: 2,
    height: spacing.sm * 2,
    backgroundColor: colors.borderLight,
  },
  lifecycleConnectorCompleted: {
    backgroundColor: colors.success,
  },
  lifecycleDot: {
    width: 24,
    height: 24,
    borderRadius: radius.full,
    borderWidth: 2,
    borderColor: colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lifecycleDotCompleted: {
    borderColor: colors.success,
    backgroundColor: colors.successLight,
  },
  lifecycleDotCurrent: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  lifecycleDotUpcoming: {
    borderColor: colors.border,
  },
  lifecycleDotInner: {
    width: 8,
    height: 8,
    borderRadius: radius.full,
    backgroundColor: colors.primary,
  },
  lifecycleLabel: {
    ...typography.styles.bodySmall,
    color: colors.textTertiary,
    textTransform: 'capitalize',
  },
  lifecycleLabelCompleted: {
    color: colors.success,
    fontWeight: '500',
  },
  lifecycleLabelCurrent: {
    color: colors.primary,
    fontWeight: '600',
  },
  lifecycleLabelUpcoming: {
    color: colors.textTertiary,
  },
  rejectedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  rejectedText: {
    ...typography.styles.label,
    color: colors.statusRejected,
  },

  // Intelligence Items
  intelligenceItem: {
    marginBottom: spacing.md,
  },
  intelligenceLabel: {
    ...typography.styles.label,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
  },
  intelligenceText: {
    ...typography.styles.bodySmall,
    color: colors.text,
    lineHeight: typography.lineHeight.relaxed,
  },
  confidenceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  confidenceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
  },
  confidenceDot: {
    width: 8,
    height: 8,
    borderRadius: radius.full,
  },
  confidenceText: {
    ...typography.styles.label,
    fontWeight: '600',
  },

  // Impact Chain
  impactChain: {
    gap: spacing.sm,
  },
  impactChainItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.xs,
  },
  impactChainNumber: {
    width: 24,
    height: 24,
    borderRadius: radius.full,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  impactChainNumberText: {
    ...typography.styles.caption,
    color: colors.primary,
    fontWeight: '600',
  },
  impactChainText: {
    ...typography.styles.bodySmall,
    color: colors.text,
    flex: 1,
  },

  // Recommended Action
  recommendedAction: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    backgroundColor: colors.primaryLight,
    padding: spacing.md,
    borderRadius: radius.lg,
  },
  recommendedActionText: {
    ...typography.styles.bodySmall,
    color: colors.text,
    flex: 1,
    lineHeight: typography.lineHeight.relaxed,
  },
  recommendationDisclaimer: {
    ...typography.styles.caption,
    color: colors.textTertiary,
    marginTop: spacing.md,
    fontStyle: 'italic',
  },

  // Verification
  verificationCard: {
    borderRadius: radius.xl,
    backgroundColor: colors.infoLight,
    gap: spacing.sm,
  },
  verificationTitle: {
    ...typography.styles.heading,
    color: colors.text,
    fontSize: typography.fontSize.md,
    marginTop: spacing.xs,
  },
  verificationText: {
    ...typography.styles.bodySmall,
    color: colors.textSecondary,
    lineHeight: typography.lineHeight.relaxed,
  },

  // Footer
  footer: {
    paddingTop: spacing.md,
    paddingBottom: spacing.xl,
  },

  // ── Real Intelligence Styles ──────────────────────────────

  intelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xs,
    flexWrap: 'wrap',
  },
  intelBadge: {
    backgroundColor: colors.infoLight,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing['2xs'],
    borderRadius: radius.sm,
  },
  intelBadgeText: {
    ...typography.styles.caption,
    color: colors.info,
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  intelDisclaimer: {
    ...typography.styles.caption,
    color: colors.textTertiary,
    marginBottom: spacing.md,
    fontStyle: 'italic',
  },
  intelBlock: {
    marginBottom: spacing.md,
  },
  intelLabel: {
    ...typography.styles.label,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
  },
  intelText: {
    ...typography.styles.bodySmall,
    color: colors.text,
    lineHeight: typography.lineHeight.relaxed,
  },
  intelMetrics: {
    flexDirection: 'row',
    gap: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.borderLight,
    marginBottom: spacing.md,
  },
  intelMetric: {
    flex: 1,
    gap: spacing.xs,
  },
  intelMetricLabel: {
    ...typography.styles.caption,
    color: colors.textSecondary,
  },
  intelMetricBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
    alignSelf: 'flex-start',
  },
  intelMetricDot: {
    width: 8,
    height: 8,
    borderRadius: radius.full,
  },
  intelMetricValue: {
    ...typography.styles.label,
    fontWeight: '600',
  },
  intelList: {
    gap: spacing.sm,
  },
  intelListItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    paddingVertical: spacing.xs,
  },
  intelListDot: {
    width: 6,
    height: 6,
    borderRadius: radius.full,
    backgroundColor: colors.primary,
    marginTop: 6,
    flexShrink: 0,
  },
  intelListText: {
    ...typography.styles.bodySmall,
    color: colors.text,
    flex: 1,
    lineHeight: typography.lineHeight.relaxed,
  },
  intelNumberedItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    paddingVertical: spacing.xs,
  },
  intelNumberBadge: {
    width: 20,
    height: 20,
    borderRadius: radius.full,
    backgroundColor: colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  intelNumberText: {
    ...typography.styles.caption,
    color: colors.primary,
    fontWeight: '600',
    fontSize: 10,
  },
  intelNumberedText: {
    ...typography.styles.bodySmall,
    color: colors.text,
    flex: 1,
    lineHeight: typography.lineHeight.relaxed,
  },
  intelVerification: {
    marginTop: spacing.sm,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  intelVerificationText: {
    ...typography.styles.caption,
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  intelLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.md,
  },
  intelLoadingText: {
    ...typography.styles.bodySmall,
    color: colors.textSecondary,
  },
  intelUnavailable: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    paddingVertical: spacing.sm,
  },
  intelUnavailableText: {
    ...typography.styles.bodySmall,
    color: colors.textSecondary,
    flex: 1,
    lineHeight: typography.lineHeight.relaxed,
  },
  intelLowConfidence: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  intelLowConfidenceText: {
    ...typography.styles.caption,
    color: colors.warning,
    flex: 1,
  },

  // ── Civic Ripple Styles ─────────────────────────────────

  rippleSection: {
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  rippleTitle: {
    ...typography.styles.heading,
    color: colors.text,
    fontSize: typography.fontSize.md,
    marginBottom: spacing.xs,
  },
  rippleSubtitle: {
    ...typography.styles.caption,
    color: colors.textSecondary,
    marginBottom: spacing.md,
  },
  rippleChain: {
    paddingLeft: spacing.sm,
  },
  rippleItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    paddingVertical: spacing.xs,
  },
  rippleConnector: {
    width: 2,
    height: spacing.md,
    backgroundColor: colors.borderLight,
    marginLeft: 5,
  },
  rippleTriggerDot: {
    width: 12,
    height: 12,
    borderRadius: radius.full,
    backgroundColor: colors.primary,
    marginTop: 4,
    flexShrink: 0,
  },
  rippleTriggerText: {
    ...typography.styles.bodySmall,
    color: colors.text,
    fontWeight: '600',
    flex: 1,
    lineHeight: typography.lineHeight.relaxed,
  },
  rippleEffectDot: {
    width: 10,
    height: 10,
    borderRadius: radius.full,
    backgroundColor: colors.warning,
    marginTop: 5,
    flexShrink: 0,
  },
  rippleEffectText: {
    ...typography.styles.bodySmall,
    color: colors.text,
    flex: 1,
    lineHeight: typography.lineHeight.relaxed,
  },
  rippleImpactDot: {
    width: 12,
    height: 12,
    borderRadius: radius.full,
    backgroundColor: '#E65100',
    marginTop: 4,
    flexShrink: 0,
  },
  rippleImpactText: {
    ...typography.styles.bodySmall,
    color: colors.text,
    fontWeight: '500',
    flex: 1,
    lineHeight: typography.lineHeight.relaxed,
  },
  rippleLevelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.md,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  rippleLevelLabel: {
    ...typography.styles.label,
    color: colors.textSecondary,
  },
  rippleLevelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
  },
  rippleLevelDot: {
    width: 8,
    height: 8,
    borderRadius: radius.full,
  },
  rippleLevelText: {
    ...typography.styles.label,
    fontWeight: '600',
  },
  rippleDisclaimer: {
    ...typography.styles.caption,
    color: colors.textTertiary,
    fontStyle: 'italic',
    marginTop: spacing.sm,
  },
});
