// ── Evidence Database Model ──────────────────────────────────────
//
// TypeScript types matching the evidence table schema defined in
// database/migrations/20260902_create_evidence_table.sql.
//
// Field names use snake_case to match Supabase/PostgreSQL responses.
// Media type and source values use lowercase to match database CHECK constraints.

// ── Enums ────────────────────────────────────────────────────────

/**
 * Allowed MIME types for evidence uploads.
 * Matches the CHECK constraint on evidence.media_type.
 */
export const EVIDENCE_MEDIA_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/heic',
  'image/heif',
] as const;

export type EvidenceMediaType = (typeof EVIDENCE_MEDIA_TYPES)[number];

/**
 * Source of the evidence image.
 * Matches the CHECK constraint on evidence.source.
 */
export const EVIDENCE_SOURCES = ['camera', 'gallery'] as const;

export type EvidenceSource = (typeof EVIDENCE_SOURCES)[number];

// ── Database Row ─────────────────────────────────────────────────

/**
 * Evidence row as returned from the database via Supabase.
 * Matches the public.evidence table schema.
 */
export interface EvidenceRow {
  id: string;
  incident_id: string;
  uploader_id: string;
  storage_path: string;
  media_type: EvidenceMediaType;
  source: EvidenceSource;
  file_size: number;
  width: number | null;
  height: number | null;
  captured_at: string | null;
  created_at: string;
}

// ── Insert Payload ───────────────────────────────────────────────

/**
 * Data required to create a new evidence record.
 * - uploader_id is derived from the authenticated session (never from client)
 * - incident_id must belong to the authenticated user (enforced by RLS)
 * - storage_path is generated by the upload service
 */
export interface CreateEvidencePayload {
  incident_id: string;
  /** uploader_id is set from auth.uid() by the service — never from client input */
  uploader_id: string;
  storage_path: string;
  media_type: EvidenceMediaType;
  source: EvidenceSource;
  file_size: number;
  width?: number;
  height?: number;
  captured_at?: string;
}

// ── Validation Constants ─────────────────────────────────────────

/**
 * Field constraints matching the database CHECK constraints.
 * Use these for client-side validation before sending to the database.
 */
export const EVIDENCE_CONSTRAINTS = {
  storagePath: { minLength: 1, maxLength: 500 },
  fileSize: {
    min: 1,
    max: 10 * 1024 * 1024, // 10 MB
    maxLabel: '10 MB',
  },
  width: { min: 1, max: 10000 },
  height: { min: 1, max: 10000 },
  maxPhotosPerIncident: 3,
} as const;

// ── Storage Configuration ────────────────────────────────────────

/**
 * Supabase Storage configuration for evidence uploads.
 * The bucket must be created manually in the Supabase dashboard
 * with public = false (private bucket).
 */
export const EVIDENCE_STORAGE = {
  bucketName: 'evidence',
  isPublic: false,
  allowedMimeTypes: EVIDENCE_MEDIA_TYPES,
  maxFileSizeBytes: EVIDENCE_CONSTRAINTS.fileSize.max,
} as const;

// ── Local Evidence (pre-upload) ──────────────────────────────────

/**
 * Evidence photo captured locally but not yet uploaded.
 * Used by the Report flow before submission.
 * Matches the EvidencePhoto interface in the report screen.
 */
export interface LocalEvidencePhoto {
  uri: string;
  width: number;
  height: number;
  source: EvidenceSource;
  /** Estimated file size in bytes (if available from device) */
  fileSize?: number;
  /** Captured timestamp from device (if available) */
  capturedAt?: string;
}

// ── Validation Helpers ───────────────────────────────────────────

/**
 * Validates a MIME type against allowed evidence types.
 */
export function isValidEvidenceMediaType(mimeType: string): mimeType is EvidenceMediaType {
  return EVIDENCE_MEDIA_TYPES.includes(mimeType as EvidenceMediaType);
}

/**
 * Validates file size against evidence constraints.
 */
export function isValidEvidenceFileSize(sizeBytes: number): boolean {
  return (
    sizeBytes >= EVIDENCE_CONSTRAINTS.fileSize.min &&
    sizeBytes <= EVIDENCE_CONSTRAINTS.fileSize.max
  );
}

/**
 * Generates a storage path for evidence upload.
 * Format: {incident_id}/{uuid}.{ext}
 *
 * The path structure ensures:
 * - Evidence is organized by incident for easy retrieval
 * - Each file has a unique name (UUID)
 * - Extension matches the media type
 */
export function generateEvidenceStoragePath(
  incidentId: string,
  mediaType: EvidenceMediaType
): string {
  const ext = mediaType.split('/')[1] || 'jpg';
  // Use a timestamp-based pseudo-UUID for client-side generation
  // In production, use crypto.randomUUID() or a proper UUID library
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 10);
  const fileId = `${timestamp}-${random}`;
  return `${incidentId}/${fileId}.${ext}`;
}
